export const cartTypes = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
    REDUCE_CART_ITEM: "REDUCE_CART_ITEM",
    CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS", 
    GET_TOTAL:"GET_TOTAL",
}